"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "uz" | "ru"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  uz: {
    "login.title": "Kirish",
    "login.username": "Foydalanuvchi nomi",
    "login.password": "Parol",
    "login.button": "Kirish",
    "login.test_credentials": "Test ma'lumotlari:",
    "login.admin_creds": "Admin: admin / admin123",
    "login.user_creds": "Foydalanuvchi: 21_169 / password123",
    "login.invalid_credentials": "Noto'g'ri foydalanuvchi nomi yoki parol.",
    "dashboard.title": "Buyurtmalar Paneli",
    "dashboard.filter_status": "Holat bo'yicha filter",
    "dashboard.all": "Barchasi",
    "dashboard.open": "Ochiq",
    "dashboard.closed": "Yopilgan",
    "dashboard.canceled": "Bekor qilingan",
    "dashboard.export_csv": "CSVga eksport",
    "dashboard.table.id": "ID",
    "dashboard.table.user": "Foydalanuvchi",
    "dashboard.table.type": "Turi",
    "dashboard.table.description": "Izoh",
    "dashboard.table.date": "Sana",
    "dashboard.table.status": "Holati",
    "dashboard.table.actions": "Amallar",
    "dashboard.action.cancel": "Bekor qilish",
    "dashboard.action.view_comments": "Sharhlarni ko'rish",
    "dashboard.action.edit": "Tahrirlash",
    "dashboard.no_orders": "Buyurtmalar topilmadi.",
    "dashboard.order_canceled_success": "Buyurtma bekor qilindi!",
    "dashboard.edit_order_modal.title": "Buyurtmani tahrirlash",
    "dashboard.edit_order_modal.submit": "Saqlash",
    "orders.title": "Mening Buyurtmalarim",
    "orders.new_order": "Yangi buyurtma",
    "orders.table.close": "Yopish",
    "orders.order_closed_success": "Buyurtma yopildi!",
    "orders.review_submitted_success": "Sharh yuborildi!",
    "orders.order_updated_success": "Buyurtma muvaffaqiyatli tahrirlandi!",
    "orders.new_order_form.title": "Yangi buyurtma yaratish",
    "orders.new_order_form.type": "Buyurtma turi",
    "orders.new_order_form.description": "Izoh",
    "orders.new_order_form.submit": "Yuborish",
    "orders.new_order_form.select_type": "Turini tanlang",
    "orders.order_type.electrician": "Elektrik",
    "orders.order_type.plumber": "Santexnik",
    "orders.order_type.handyman": "Usta",
    "orders.order_type.carpenter": "Duradgor",
    "orders.order_type.other": "Boshqa",
    "orders.review_modal.title": "Sharh qoldirish",
    "orders.review_modal.rating": "Baho",
    "orders.review_modal.comment": "Izoh",
    "orders.review_modal.submit": "Yuborish",
    "orders.review_modal.cancel": "Bekor qilish",
    "create_user.title": "Yangi foydalanuvchi qo'shish",
    "create_user.apartment_number": "Kvartira raqami",
    "create_user.room_number": "Xonadon raqami",
    "create_user.members_count": "A'zolar soni", // Yangi tarjima
    "create_user.generated_login": "Hosil qilingan login:",
    "create_user.add_user": "Foydalanuvchi qo'shish",
    "create_user.user_added_success": "Foydalanuvchi muvaffaqiyatli qo'shildi!",
    "create_user.password": "Parol",
    "statistics.title": "Statistika",
    "statistics.total_orders": "Jami buyurtmalar",
    "statistics.active_orders": "Faol (ochiq) buyurtmalar",
    "statistics.closed_orders": "Yopilgan buyurtmalar",
    "statistics.canceled_orders": "Bekor qilingan buyurtmalar",
    "statistics.most_active_users": "Eng faol foydalanuvchilar",
    "reviews.title": "Sharhlar ro'yxati",
    "reviews.table.order_id": "Buyurtma ID",
    "reviews.table.user": "Foydalanuvchi",
    "reviews.table.rating": "Baho",
    "reviews.table.comment": "Izoh",
    "reviews.no_reviews": "Sharhlar topilmadi.",
    "reviews.search_placeholder": "ID, foydalanuvchi nomi yoki izoh bo'yicha qidirish...",
    "users.search_placeholder": "Foydalanuvchi nomi, kvartira yoki xona bo'yicha qidirish...",
    "users.edit_user_modal.title": "Foydalanuvchini tahrirlash",
    "users.edit_user_modal.description": "{username} foydalanuvchisi ma'lumotlarini yangilang.",
    "users.username_exists": "Bu kvartira va xona raqami bilan foydalanuvchi allaqachon mavjud.",
    "users.user_updated_success": "Foydalanuvchi ma'lumotlari muvaffaqiyatli yangilandi!",
    "profile.title": "Mening profilim",
    "profile.your_profile": "Sizning profilingiz",
    "profile.view_and_edit_details": "Profil ma'lumotlaringizni ko'ring va tahrirlang.",
    "profile.edit_profile": "Profilni tahrirlash",
    "profile.update_apartment_room": "Kvartira va xona raqamingizni yangilang.",
    "sidebar.dashboard": "Buyurtmalar",
    "sidebar.create_user": "Yangi foydalanuvchi",
    "sidebar.users_list": "Xonadonlar ro'yxati",
    "sidebar.statistics": "Statistika",
    "sidebar.reviews": "Sharhlar",
    "sidebar.logout": "Chiqish",
    "common.confirm": "Tasdiqlash",
    "common.cancel": "Bekor qilish",
    "common.success": "Muvaffaqiyat!",
    "common.error": "Xato!",
    "common.no_data": "Ma'lumotlar topilmadi.",
    "common.edited": "tahrirlangan",
    "common.info": "Ma'lumot",
    "common.not_set": "O'rnatilmagan",
    "common.no_changes_detected": "O'zgarishlar aniqlanmadi.",
  },
  ru: {
    "login.title": "Вход",
    "login.username": "Имя пользователя",
    "login.password": "Пароль",
    "login.button": "Войти",
    "login.test_credentials": "Тестовые данные:",
    "login.admin_creds": "Админ: admin / admin123",
    "login.user_creds": "Пользователь: 21_169 / password123",
    "login.invalid_credentials": "Неверное имя пользователя или пароль.",
    "dashboard.title": "Панель заказов",
    "dashboard.filter_status": "Фильтр по статусу",
    "dashboard.all": "Все",
    "dashboard.open": "Открытые",
    "dashboard.closed": "Закрытые",
    "dashboard.canceled": "Отмененные",
    "dashboard.export_csv": "Экспорт в CSV",
    "dashboard.table.id": "ID",
    "dashboard.table.user": "Пользователь",
    "dashboard.table.type": "Тип",
    "dashboard.table.description": "Описание",
    "dashboard.table.date": "Дата",
    "dashboard.table.status": "Статус",
    "dashboard.table.actions": "Действия",
    "dashboard.action.cancel": "Отменить",
    "dashboard.action.view_comments": "Посмотреть комментарии",
    "dashboard.action.edit": "Редактировать",
    "dashboard.no_orders": "Заказы не найдены.",
    "dashboard.order_canceled_success": "Заказ отменен!",
    "dashboard.edit_order_modal.title": "Редактировать заказ",
    "dashboard.edit_order_modal.submit": "Сохранить",
    "orders.title": "Мои заказы",
    "orders.new_order": "Новый заказ",
    "orders.table.close": "Закрыть",
    "orders.order_closed_success": "Заказ закрыт!",
    "orders.review_submitted_success": "Отзыв отправлен!",
    "orders.order_updated_success": "Заказ успешно обновлен!",
    "orders.new_order_form.title": "Создать новый заказ",
    "orders.new_order_form.type": "Тип заказа",
    "orders.new_order_form.description": "Описание",
    "orders.new_order_form.submit": "Отправить",
    "orders.new_order_form.select_type": "Выберите тип",
    "orders.order_type.electrician": "Электрик",
    "orders.order_type.plumber": "Сантехник",
    "orders.order_type.handyman": "Мастер",
    "orders.order_type.carpenter": "Плотник",
    "orders.order_type.other": "Другое",
    "orders.review_modal.title": "Оставить отзыв",
    "orders.review_modal.rating": "Оценка",
    "orders.review_modal.comment": "Комментарий",
    "orders.review_modal.submit": "Отправить",
    "orders.review_modal.cancel": "Отмена",
    "create_user.title": "Добавить нового пользователя",
    "create_user.apartment_number": "Номер квартиры",
    "create_user.room_number": "Номер комнаты",
    "create_user.members_count": "Количество жильцов", // Yangi tarjima
    "create_user.generated_login": "Сгенерированный логин:",
    "create_user.add_user": "Добавить пользователя",
    "create_user.user_added_success": "Пользователь успешно добавлен!",
    "create_user.password": "Пароль",
    "statistics.title": "Статистика",
    "statistics.total_orders": "Всего заказов",
    "statistics.active_orders": "Активные (открытые) заказы",
    "statistics.closed_orders": "Закрытые заказы",
    "statistics.canceled_orders": "Отмененные заказы",
    "statistics.most_active_users": "Самые активные пользователи",
    "reviews.title": "Список отзывов",
    "reviews.table.order_id": "ID заказа",
    "reviews.table.user": "Пользователь",
    "reviews.table.rating": "Оценка",
    "reviews.table.comment": "Комментарий",
    "reviews.no_reviews": "Отзывы не найдены.",
    "reviews.search_placeholder": "Поиск по ID, имени пользователя или комментарию...",
    "users.search_placeholder": "Поиск по имени пользователя, квартире или комнате...",
    "users.edit_user_modal.title": "Редактировать пользователя",
    "users.edit_user_modal.description": "Обновите данные пользователя {username}.",
    "users.username_exists": "Пользователь с этим номером квартиры и комнаты уже существует.",
    "users.user_updated_success": "Данные пользователя успешно обновлены!",
    "profile.title": "Мой профиль",
    "profile.your_profile": "Ваш профиль",
    "profile.view_and_edit_details": "Просмотр и редактирование данных профиля.",
    "profile.edit_profile": "Редактировать профиль",
    "profile.update_apartment_room": "Обновите номер квартиры и комнаты.",
    "sidebar.dashboard": "Заказы",
    "sidebar.create_user": "Новый пользователь",
    "sidebar.users_list": "Список квартир",
    "sidebar.statistics": "Статистика",
    "sidebar.reviews": "Отзывы",
    "sidebar.logout": "Выход",
    "common.confirm": "Подтвердить",
    "common.cancel": "Отмена",
    "common.success": "Успешно!",
    "common.error": "Ошибка!",
    "common.no_data": "Данные не найдены.",
    "common.edited": "изменено", // O'zgartirildi
    "common.info": "Информация",
    "common.not_set": "Не установлено",
    "common.no_changes_detected": "Изменений не обнаружено.",
  },
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("uz") // Default to Uzbek

  const t = (key: string): string => {
    return translations[language][key] || key // Fallback to key if translation not found
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { LanguageContext }
